version: '2'
services:
  cb1:
    image: 'couchbase/server:6.5.1'
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
    volumes:
        - "~/couchbase/cb1:/opt/couchbase/var"

  zookeeper-server:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '9898:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka-server1:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server
  employee-service:
    image: 'indralok/employee-service:1.0.2'
    ports:
      - '8989:8080'